[project]
authors = [{name = "Randy J", email = "randy@astruct.co"}]
description = "Simple manifest example."
name = "pytproject-example"
requires-python = "3.10"
version = "0.1.0"

dependencies = [
    "fastrandom==0.1.0",
]
