name: Fetch embedded code snippets in markdown files and embed them.

on:
  push:
    branches:
      - blog/*
  pull_request:
    branches:
      - main

jobs:
  embed-code-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: Analogous-Structures-Labs/markdown-embed-code@fix
        with:
          markdown: "*.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Embed code snippets."
          silent: true
