name: Fetch embedded code snippets in markdown files and embed them.

on:
  push:
    branches:
      - blog/*
  pull_request:
    branches:
      - main

jobs:
  embed-code-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: refs/heads/${{ github.head_ref }}

      - uses: tdabasinskas/markdown-embed-code@fork
        with:
          markdown: "*.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Embed code snippets."
          silent: true
